# Generated by Django 2.0.3 on 2018-03-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=200)),
                ('eje', models.CharField(max_length=250)),
                ('objetivo', models.TextField()),
                ('estrategia', models.TextField()),
                ('linea_accion', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre_formato', models.CharField(blank=True, max_length=140, null=True)),
                ('dimension_medir', models.CharField(max_length=140)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('metodo_calculo', models.CharField(blank=True, max_length=140, null=True)),
                ('frecuencia_medicion', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(max_length=140)),
                ('meta_programada', models.CharField(blank=True, max_length=50, null=True)),
                ('sentido_indicador', models.CharField(default='Ascendente', max_length=50)),
                ('medicion_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_base', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('elaboro', models.CharField(max_length=140)),
            ],
        ),
    ]
